image: markadams/chromium-xvfb

stages:
  - linting
  - testing
  - building
  - packaging
  - deploying

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

before_script:
  - apt-get clean
  - apt-get update
  - curl -sL https://deb.nodesource.com/setup_6.x | bash -
  - apt-get install -y nodejs git
  - npm -v
  - node -v
  - npm install --silent

lint:
  stage: linting
  script:
    - npm run lint
  
test:
  stage: testing
  script:
    - npm test
  allow_failure: true
  environment:
    name: testing

codecov:
  stage: testing
  script:
    - npm run codecov
  environment:
    name: testing

build:
  stage: building
  script:
    - npm run build:prod
  artifacts:
    name: "CI_PROJECT_NAME-$CI_COMMIT_REF_NAME:CI_COMMIT_SHORT_SHA"
    paths:
      - dist/
