interface AuthConfig {
  CLIENT_ID: string;
  CLIENT_DOMAIN: string;
  AUDIENCE: string;
  REDIRECT: string;
  SCOPE: string;
  API_HOST_URL: string;
}

export const AUTH_CONFIG: AuthConfig = {
  CLIENT_ID: AUTH0_CLIENT_ID,
  CLIENT_DOMAIN: AUTH0_CLIENT_DOMAIN,
  AUDIENCE: AUTH0_AUDIENCE,
  REDIRECT: AUTH0_REDIRECT,
  SCOPE: AUTH0_SCOPE,
  API_HOST_URL: API_HOST
};
